FROM s390x/ruby:3

#RUN apt-get update && apt-get install -y redis

WORKDIR /opt/todos/

COPY . .
# RUN gem install bundler:2.1.4
RUN gem install 'json_pure' 'sinatra' 'redis' 'webrick'

#RUN bundle config --global frozen 1 && \
#    bundle config set deployment 'true' && \
#    bundle install
# Persistent volumes
EXPOSE 4567

CMD ["ruby", "server.rb"]

