apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: proto-todos-3-dev
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: proto-todos-3-dev-service-account
    namespace: proto-todos-3-dev
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
