{{ if not eq .Values.tag "latest"}}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: todosdblatest-snap-{{ .Values.tag }}
  namespace: {{ .Release.Namespace }}
spec:
  volumeSnapshotClassName: {{ .Values.vsc }}-snapclass
  source:
    persistentVolumeClaimName: todosdblatest
{{ end }}