apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos{{ .Values.tag }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos{{ .Values.tag }}
  strategy: {}
  template:
    metadata:
      labels:
        app: todos{{ .Values.tag }}
    spec:
      containers:
        - name: www
          image: docker.io/coulof/todos:{{ .Values.tag }}
          env:
            - name: COMMIT
              value: "{{ .Values.commit }}"
            - name: REDIS_HOST
              value: redis{{ .Values.tag }}
            - name: REDIS_PORT
              value: "6379" 
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: todos-{{ .Values.tag }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: todos{{ .Values.tag }}
  # type: LoadBalancer
    {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
    clusterIP: {{ .Values.service.clusterIP }}
    {{- end }}
  ports:
    - port: 80
      targetPort: 4567
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort}}
      nodePort: {{ .Values.service.nodePort}}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}