apiVersion: v1
kind: ServiceAccount
metadata:
    name: todos
    namespace: {{ .Release.Namespace }}
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: todos{{ .Values.tag }}
    namespace: {{ .Release.Namespace }}
spec:
    serviceName: todos{{ .Values.tag }}
    selector:
        matchLabels:
          app: todos{{ .Values.tag }}
    template:
      metadata:
        labels:
          app: todos{{ .Values.tag }}
      spec:
        serviceAccount: todos
        containers:
          - name: todos{{ .Values.tag }}
            image: docker.io/coulof/todos:{{ .Values.tag }}
            imagePullPolicy: Always
            env:
            - name: COMMIT
              value: "{{ .Values.commit }}"
            volumeMounts:
              - mountPath: "/opt/todos/data/"
                name: todosdb{{ .Values.tag }}
        volumes:
          - name: todosdb{{ .Values.tag }}
            persistentVolumeClaim:
              claimName: todosdb{{ .Values.tag }}
---
apiVersion: v1
kind: Service
metadata:
  name: todos-{{ .Values.tag }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: todos{{ .Values.tag }}
  # type: LoadBalancer
    {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
    clusterIP: {{ .Values.service.clusterIP }}
    {{- end }}
  ports:
    - port: 80
      targetPort: 4567
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort}}
      nodePort: {{ .Values.service.nodePort}}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}